name: must-render
version: 0.1.0.0
license: BSD3
author: "Aleksey Danilevsky"
maintainer: "alexey.danilevsky@gmail.com"
copyright: "2020 Aleksey Danilevsky"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/mustache-doc-build#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - http-types
  - utf8-string
  - mtl
  - mustache
  - text
  - wai
  - warp
  - yaml

library:
  source-dirs: src

executables:
  must-render:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - must-render

tests:
  must-render-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - must-render
